config/routes.rb
Rails.application.routes.draw do

  resources :cats, except: :destroy

  resources :cat_rental_requests, only: [:new, :create]

  patch "cat_rental_requests/:id/approve", to: "cat_rental_requests#approve", as: "approve"
  patch "cat_rental_requests/:id/deny", to: "cat_rental_requests#deny", as: "deny"

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = [
    "yellow",
    "black",
    "white",
    "gray",
    "orange",
    "colorful"
  ]

  SEXES = [
    "M",
    "F"
  ]

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: COLORS
  validates :sex, inclusion: SEXES

  has_many :rental_requests,
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest

  def age
    Date.today.year - birth_date.year
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = [
    "PENDING",
    "APPROVED",
    "DENIED"
  ]

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: STATUSES
  validate :does_not_overlap_approved_request
  validate :cat_exists

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat


  def overlapping_requests
    CatRentalRequest.where(cat_id: cat_id)
      .where("start_date BETWEEN ? AND ?
        OR end_date BETWEEN ? AND ?
        OR(
        start_date < ? AND end_date > ?
        )", start_date, end_date, start_date, end_date, start_date, end_date)
      .where.not(id: id)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors[:start_date] << "Overlaps with other rental"
    end
  end

  def cat_exists
    cat = Cat.exists?(cat_id)
    unless cat
      errors[:cat_id] << "Must exist"
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: 'PENDING')
  end

  def approve!
    ActiveRecord::Base.transaction do
      update(status: "APPROVED")
      overlapping_pending_requests.update_all(status: "DENIED")
    end
  end

  def deny!
    update(status: 'DENIED')
  end

  def pending?
    status == 'PENDING'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new

  end

  def create
    @rental = CatRentalRequest.new(rental_params)
    @rental.status = 'PENDING'
    if @rental.save
      redirect_to cat_url(@rental.cat_id)
    else
      render :new
    end
  end

  def approve
    @rental = CatRentalRequest.find(params[:id])
    @rental.approve!
    redirect_to cat_url(@rental.cat_id)
  end

  def deny
    @rental = CatRentalRequest.find(params[:id])
    @rental.deny!
    redirect_to cat_url(@rental.cat_id)
  end

  private

  def rental_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    render :show
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Add new rental</h1>

<form action= "<%= cat_rental_requests_url %>" method="POST">
  <label for="rental_cat_id">Choose cat</label>
  <select id="rental_cat_id" name="rental[cat_id]">
    <% Cat.all.each do |kitty| %>
      <option value=" <%= kitty.id %>"> <%= kitty.name %></option>
    <% end %>
  </select>
  <br>

    <label for="rental_start_date">Start date</label>
    <input type="date" id="rental_start_date" name= "rental[start_date]" />
    <br />

    <label for="rental_end_date">End date</label>
    <input type="date" id="rental_end_date" name= "rental[end_date]" />
    <br />

    <input type="submit" value="Request rental" />
</form>

app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <form action="<%= cat_url(cat) %>" method = "POST">
    <input type ="hidden" name = "_method", value = "PATCH" />
<% else %>
  <form action="<%= cats_url %>" method = "POST">
<% end %>


  <label for="cat_name">Cat Name</label>
  <input type="text" id="cat_name" name="cat[name]" value= "<%= cat.name %>" />

  <br />

  <label for="cat_sex_M">Male</label>
  <input type="radio" id="cat_sex_M" value="M" name = "cat[sex]" <%= "checked" if cat.sex == 'M' %> />
  <label for="cat_sex_F">Female</label>
  <input type="radio" id="cat_sex_F" value="F" name = "cat[sex]" <%= "checked" if cat.sex == 'F' %> />

  <br />

  <label for="cat_color">Color </label>
  <select id="cat_color" name="cat[color]">
    <% unless cat.persisted? %>
      <option disabled selected>
        -- Please select color --
      </option>
    <% end %>
    <%Cat::COLORS.each do |color| %>
      <option value = "<%= color %>" <%= "selected" if cat.color == color %>> <%= color.capitalize %> </option>
    <% end %>
  </select>

  <br />

  <label for="cat_birthday">Birthday</label>
  <input type="date" id="cat_birthday" name="cat[birth_date]" value= "<%= cat.birth_date %>" />

  <br />

  <label for="cat_description">Description</label>
  <textarea id = "cat_description" name="cat[description]"> <%= cat.description %></textarea>

  <br />
  <br />

  <input type="submit" value= "<%= cat.persisted? ? "Update cat" : "Add cat" %>" />
</form>

app/views/cats/edit.html.erb
<h1>Edit cat</h1>
<%= render 'form', cat: @cat %>

app/views/cats/index.html.erb
<h1>All cats</h1>
<ul>
<% @cats.each do |cat| %>
  <li>
    <%= link_to cat.name, cat_url(cat.id)  %>
  </li>
<% end %>
</ul>

<br />

<%= link_to "New Cat!!!!", new_cat_url %>
<br>

 <%= link_to "Rental request", new_cat_rental_request_url %> 

app/views/cats/new.html.erb
<h1>Add cat</h1>

<%= render 'form', cat: @cat %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<h3> Cat details </h3>
<table border="1">
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Age</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<h3>Rentals</h3>
<table border = "1">
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
    <% @cat.rental_requests.order(:start_date).each do |rental| %>
      <tr>
        <td><%= rental.start_date %></td>
        <td><%= rental.end_date %></td>
        <% if rental.pending? %>
          <td> <%= button_to "Approve", approve_url(rental), method: :patch %>
            <%= button_to "Deny", deny_url(rental), method: :patch %> </td>
        <% else %>
          <td><%= rental.status %></td>
        <% end %>
      </tr>
    <% end  %>
</table>

<br>
<br>

<%= link_to "All cats", cats_url %>
<br />
<%= link_to "Edit cat", edit_cat_url(@cat) %>
<br>
<!-- For debugging: -->
<!-- <%= link_to "Rental request", new_cat_rental_request_url %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>